#!/usr/bin/env node
/**
 * Copy the app's own stylesheet into the hero demo, cut down to what the demo
 * uses.
 *
 *   node scripts/sync-app-ui.mjs <path-to-app>/jarvis/ui/web/dist/assets
 *
 * The hero demo (src/components/demo/app/) is a clone of the app built from
 * the app's own markup — the same elements and the same class names as its
 * components. Styled by the app's compiled CSS, it renders exactly as the app
 * does, and a restyle of the app reaches the demo by running this script
 * again rather than by someone redrawing it by eye.
 *
 * The full sheet is ~285 KB. Only rules whose classes all appear somewhere in
 * the clone's source are kept, plus every rule that names no class at all
 * (the theme variables, the base element rules) and the keyframes those kept
 * rules animate with. @font-face is dropped: the demo ships its own two font
 * files and declares them itself (AppFrame.tsx).
 *
 * Run it after changing the clone's markup too — a class that is new to the
 * clone is not in the cut-down sheet until this runs.
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import postcss from "postcss";

const ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const CLONE_DIR = join(ROOT, "src", "components", "demo", "app");
const OUT = join(CLONE_DIR, "app.css");

const assets = process.argv[2];
if (!assets) {
  console.error("usage: node scripts/sync-app-ui.mjs <app>/jarvis/ui/web/dist/assets");
  process.exit(2);
}

// The app's main sheet is the largest index-*.css in its build output.
const sheet = readdirSync(assets)
  .filter((n) => /^index-.*\.css$/.test(n))
  .map((n) => ({ n, size: statSync(join(assets, n)).size }))
  .sort((a, b) => b.size - a.size)[0];
if (!sheet) {
  console.error(`no index-*.css in ${resolve(assets)}`);
  process.exit(1);
}

// Every token the clone's source could be naming as a class. Over-inclusive
// on purpose: a stray word that happens to be a class name costs one rule, a
// missed class costs a broken look.
const used = new Set();
for (const name of readdirSync(CLONE_DIR)) {
  if (!/\.(tsx?|jsx?)$/.test(name)) continue;
  const text = readFileSync(join(CLONE_DIR, name), "utf8");
  // Split on whitespace, quotes and braces only: a Tailwind class can hold
  // brackets, commas, `=` and `>` (`data-[x=true]:…`, `[&>.a]:…`,
  // `transition-[a,b]`), and splitting on those would drop its rule.
  for (const token of text.split(/[\s"'`{}]+/)) if (token) used.add(token);
}

/** The classes a selector needs, unescaped (`.hover\:bg-x:hover` -> `hover:bg-x`). */
function classesOf(selector) {
  const out = [];
  const re = /\.((?:\\.|[\w-])+)/g;
  let m;
  while ((m = re.exec(selector))) out.push(m[1].replace(/\\(.)/g, "$1"));
  return out;
}

function selectorWanted(selector) {
  // A class inside :is()/:where()/:not() is a context, not a requirement of
  // the element itself (`.dark\:x:is(.dark *)`), so only the leading part is
  // checked strictly; `dark` is always present on the clone's root.
  return classesOf(selector).every((c) => c === "dark" || used.has(c));
}

const root = postcss.parse(readFileSync(join(assets, sheet.n), "utf8"));
const animations = new Set();

root.walkRules((rule) => {
  if (rule.parent?.type === "atrule" && /keyframes$/i.test(rule.parent.name)) return;
  const kept = rule.selectors.filter(selectorWanted);
  if (kept.length === 0) {
    rule.remove();
    return;
  }
  rule.selectors = kept;
  rule.walkDecls(/^animation(-name)?$/, (decl) => {
    for (const word of decl.value.split(/[\s,]+/)) animations.add(word);
  });
});

root.walkAtRules((at) => {
  if (at.name === "font-face") at.remove();
  else if (/keyframes$/i.test(at.name) && !animations.has(at.params.trim())) at.remove();
});
// Media and supports blocks left empty by the cut.
root.walkAtRules((at) => {
  if (at.nodes && at.nodes.length === 0) at.remove();
});

const header =
  "/* GENERATED by scripts/sync-app-ui.mjs from the app's " + sheet.n + " — do not edit by hand. */\n";
const css = header + root.toString().replace(/\n{2,}/g, "\n");
writeFileSync(OUT, css);
console.log(`app.css: ${(css.length / 1024).toFixed(1)} KB from ${(sheet.size / 1024).toFixed(1)} KB (${sheet.n})`);
